### ISSUE TITLE
missing dataset

### ISSUE THREAD

**Issue by danamariellanes** [jvendrow/EEG-Classification#1]
Hi I'd like to know where are the numpy files that were used in this code. Thank you.

**Comment by jvendrow** [comment]
Hi! I don't have the raw data available (this was from a class project many years ago) but here is the link to the webpage for the original competition where the data is from:

[https://bbci.de/competition/iv/](https://bbci.de/competition/iv/)

I believe the dataset is Dataset 2a. Hope this helps!
